<a href="https://www.kaggle.com/code/yanakutyshenko/notebook64fb3dee4d?scriptVersionId=355809744" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

Імпорт модулів

In [2]:
import torch

# Завдання 1

Перегляньте інформацію про доступні процесори, та виведіть про них інформацію

In [3]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.device_count())

if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

True
2
Tesla T4


# Завдання 2
Підключіться до процесора GPU, та знову виведіть інформацію про доступні процесори

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Device: cuda
GPU: Tesla T4


# Завдання 3
Створіть випадковий тензор розміру (2, 3). Виведіть інформацію про його:

* розмір
* тип даних
* процесор
* наявність градієнта

In [5]:
x = torch.rand(2, 3, device=device)

print("Тензор:")
print(x)

print("Розмір:", x.shape)
print("Тип даних:", x.dtype)
print("Процесор:", x.device)
print("Наявність градієнта:", x.requires_grad)

Тензор:
tensor([[0.9892, 0.9809, 0.3115],
        [0.4927, 0.7751, 0.1289]], device='cuda:0')
Розмір: torch.Size([2, 3])
Тип даних: torch.float32
Процесор: cuda:0
Наявність градієнта: False


# Завдання 4

Створіть 2 тензора розміру 100. Виведіть
* суму векторів
* частку векторів(перед цим замініть один елемент на 0)
* максимальне та мінімальне значення(методи .min() .max())
* середнє значення(метод .mean())
* квадрад різниці
* середнє значення квадрату різниці

In [6]:
x1 = torch.rand(100, device=device)
x2 = torch.rand(100, device=device)

x2[0] = 0

print("Сума векторів:")
print(x1 + x2)

print("Частка векторів:")
print(x1 / x2)

print("Максимальне значення:", x1.max())
print("Мінімальне значення:", x1.min())

print("Середнє значення:", x1.mean())

squared_difference = (x1 - x2) ** 2

print("Квадрат різниці:")
print(squared_difference)

print("Середнє значення квадрату різниці:", squared_difference.mean())

Сума векторів:
tensor([0.1719, 0.7470, 1.1971, 1.3970, 0.3682, 0.9012, 0.9092, 1.0483, 0.7791,
        1.5328, 0.6065, 0.3145, 0.8386, 1.3317, 1.3571, 0.6371, 1.1797, 0.0531,
        1.7911, 1.2331, 0.3126, 0.5163, 1.4585, 0.6826, 1.8239, 1.0474, 1.3168,
        1.2269, 1.0430, 0.8816, 0.6917, 0.8618, 0.5694, 1.5893, 0.9145, 0.9613,
        0.1357, 1.1658, 0.5194, 0.9629, 1.3329, 0.7927, 1.2249, 0.2722, 1.3472,
        0.9616, 1.0062, 1.5312, 1.1720, 0.8576, 0.6000, 0.7932, 1.6113, 1.1881,
        1.5448, 0.9666, 0.5108, 0.8526, 0.9175, 0.3960, 0.5711, 0.5726, 1.8484,
        0.9527, 0.7178, 0.7622, 0.7457, 0.6746, 1.2083, 0.7724, 0.8608, 1.8440,
        0.3338, 1.0521, 0.7752, 1.1678, 0.1246, 0.7548, 0.7833, 0.5828, 0.9076,
        1.3407, 1.2438, 0.3276, 0.8961, 1.3529, 0.9179, 0.8389, 0.6151, 0.6573,
        0.4641, 0.9428, 1.5300, 0.6777, 1.9428, 0.1960, 0.7222, 0.4529, 1.4224,
        0.5312], device='cuda:0')
Частка векторів:
tensor([       inf, 4.8633e+00, 1.2928e+00, 1.3832e+00

# Завдання 5

У вашому розпорядженні є нейронна мережа, яка прогнозує **орієнтовну ціну квартири** на основі двох **ознак**:

* **площі квартири** (у квадратних метрах);
* **кількості кімнат**.

Вам надано готовий клас `NeuralNetwork` із методом `predict`.

1. Створіть екземпляр класу `NeuralNetwork`, передайте як параметр `device`.
2. За допомогою методу `predict()` визначте прогнозовану ціну квартири, яка:
   * має площу **65 м²**;
   * має **2 кімнати**.
     
3. Для цього створіть тензор із відповідними числами та скористайтесь методом `predict()`.
4. Усі нейромережі очікують дані розміру `(N, K)`, де:
   * `N` — кількість об'єктів, для яких виконується прогноз;
   * `K` — кількість ознак. У цьому випадку їх дві — **площа квартири та кількість кімнат**.

5. Спробуйте скористатись методом `predict()` разом із `torch.no_grad()`:

```python
with torch.no_grad():
    price = model.predict(...)
```

**Завдання:** отримайте прогнозовану ціну квартири та виведіть результат на екран.


In [8]:
import torch


class NeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [[3.3, -38.]],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [176.],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 2:
            raise ValueError(
                f"Очікується 2 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою (float32 або float64)."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        return X @ self.W.T + self.b


In [9]:
model = NeuralNetwork(device=device)

X = torch.tensor([[65.0, 2.0]], device=device)

with torch.no_grad():
    price = model.predict(X)

print("Прогнозована ціна:", price)# Ваш код


Прогнозована ціна: tensor([[314.5000]], device='cuda:0')


# **Завдання 6**

У таблиці наведено інформацію про три квартири.

| **Квартира** | **Площа (м²)** | **Кількість кімнат** |
| ------------ | -------------: | -------------------: |
| Квартира 1   |             40 |                    1 |
| Квартира 2   |             60 |                    3 |
| Квартира 3   |             100 |                    2 |

Виконайте наступні кроки:

1. Створіть **три окремі тензори** (`X1`, `X2`, `X3`), кожен з яких містить дані про одну квартиру.
2. За допомогою методу `predict()` обчисліть **прогнозовану ціну** для кожної квартири окремо.
3. Створіть **один тензор** `X` розміру **(3, 2)**, де:
   * кожен рядок відповідає одній квартирі;
   * перший стовпець — площа квартири;
   * другий стовпець — кількість кімнат.

4. За допомогою одного виклику `predict(X)` отримайте **прогнозовану ціну одразу для всіх трьох квартир**.
5. Виведіть розмір тензору з трьома прогнозованими цінами, який ви отримали на кроці 4.
6. Порівняйте результати, отримані окремими викликами `predict()` та одним спільним викликом `predict(X)`.


In [10]:
X1 = torch.tensor([[40.0, 1.0]], device=device)
X2 = torch.tensor([[60.0, 3.0]], device=device)
X3 = torch.tensor([[100.0, 2.0]], device=device)

with torch.no_grad():
    price1 = model.predict(X1)
    price2 = model.predict(X2)
    price3 = model.predict(X3)

print("Квартира 1:", price1)
print("Квартира 2:", price2)
print("Квартира 3:", price3)

X = torch.tensor([
    [40.0, 1.0],
    [60.0, 3.0],
    [100.0, 2.0]
], dtype=torch.float32, device=device)

with torch.no_grad():
    y_pred = model.predict(X)

print("Спільний прогноз:")
print(y_pred)

print("Розмір:", y_pred.shape)

Квартира 1: tensor([[270.]], device='cuda:0')
Квартира 2: tensor([[260.]], device='cuda:0')
Квартира 3: tensor([[430.]], device='cuda:0')
Спільний прогноз:
tensor([[270.],
        [260.],
        [430.]], device='cuda:0')
Розмір: torch.Size([3, 1])


# Завдання 7

Три квартири були продані, і стали відомі їхні **реальні ціни**.

| Квартира   | Реальна ціна (1000$) |
| ---------- | ---------------: |
| Квартира 1 |           210 |
| Квартира 2 |          310 |
| Квартира 3 |          360 |

Нехай прогноз моделі збережений у змінній `y_pred`, а реальні значення — у `y_true`.

Визначте, **наскільки модель помилилася**, використавши два різних підходи.

### Варіант 1

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Обчисліть середнє значення цієї різниці за допомогою `torch.mean()`.

### Варіант 2

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Позбудьтеся від'ємних значень за допомогою `torch.abs()`.
3. Обчисліть середнє значення отриманих помилок.

### Запитання

1. Який із двох варіантів краще характеризує якість моделі? Поясніть свою відповідь.
2. Напишіть функцію `loss_fn()`, яка реалізує обраний варіант.

```python
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    ...
```




In [11]:
y_true = torch.tensor([
    [210.0],
    [310.0],
    [360.0]
], dtype=torch.float32, device=device)

difference = y_pred - y_true

mean_difference = torch.mean(difference)
mean_absolute_error = torch.mean(torch.abs(difference))

print("Середня різниця:", mean_difference)
print("Середня абсолютна помилка:", mean_absolute_error)

def loss_fn(y_pred, y_true):
    return torch.mean(torch.abs(y_pred - y_true))

loss = loss_fn(y_pred, y_true)

print("Loss:", loss)

Середня різниця: tensor(26.6667, device='cuda:0')
Середня абсолютна помилка: tensor(60., device='cuda:0')
Loss: tensor(60., device='cuda:0')


# Завдання 8

У вашому розпорядженні є вчитель, який може навчити нейронну мережу робити точніші прогнози **цін на квартири**.

Клас `Teacher` вже реалізований. Під час створення об'єкта необхідно передати модель, яку потрібно навчати:

```python
teacher = Teacher(model)
```

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Виведіть тензор `X`, який містить дані про квартири:
   * площу квартири;
   * кількість кімнат.

3. Виведіть тензор `y_true` з **реальними цінами квартир**.
4. Отримайте прогноз моделі `y_pred`.
5. Виведіть прогнозовані ціни квартир.
6. За допомогою власної функції `loss_fn()` обчисліть помилку моделі.
7. Виведіть значення помилки.
8. Скористайтеся методом `teach()` класу `Teacher`, передавши йому обчислену помилку.
9. Після навчання знову отримайте прогноз `y_pred`.
10. Виведіть нові прогнозовані ціни квартир.
11. Знову обчисліть та виведіть помилку.
12. Зробіть висновок: **чи стала модель прогнозувати ціни квартир точніше після одного кроку навчання?**



In [12]:
import torch


class Teacher:
    def __init__(self, model, lr=0.02):
        """
        Створює вчителя для навчання моделі.

        Параметри:
            model (NeuralNetwork): модель, яку потрібно навчати.
            lr (float): швидкість навчання.
        """
        self.model = model

        self.optimizer = torch.optim.SGD(
            [model.W, model.b],
            lr=lr
        )

    def teach(self, loss):
        """
        Виконує один крок навчання.

        Параметри:
            loss (torch.Tensor): значення функції втрат.
        """
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()


In [13]:
teacher = Teacher(model)

X = torch.tensor([
    [40.0, 1.0],
    [60.0, 3.0],
    [100.0, 2.0]
], dtype=torch.float32, device=device)

y_true = torch.tensor([
    [210.0],
    [310.0],
    [360.0]
], dtype=torch.float32, device=device)

y_pred = model.predict(X)

print("X:")
print(X)

print("y_true:")
print(y_true)

print("y_pred:")
print(y_pred)

loss = loss_fn(y_pred, y_true)

print("Помилка до навчання:", loss)

teacher.teach(loss)

y_pred = model.predict(X)

print("Нові прогнози:")
print(y_pred)

loss = loss_fn(y_pred, y_true)

print("Помилка після навчання:", loss)

X:
tensor([[ 40.,   1.],
        [ 60.,   3.],
        [100.,   2.]], device='cuda:0')
y_true:
tensor([[210.],
        [310.],
        [360.]], device='cuda:0')
y_pred:
tensor([[270.],
        [260.],
        [430.]], device='cuda:0', grad_fn=<AddBackward0>)
Помилка до навчання: tensor(60., device='cuda:0', grad_fn=<MeanBackward0>)
Нові прогнози:
tensor([[248.6600],
        [227.9933],
        [376.6600]], device='cuda:0', grad_fn=<AddBackward0>)
Помилка після навчання: tensor(45.7756, device='cuda:0', grad_fn=<MeanBackward0>)


# Завдання 9

Одного кроку навчання недостатньо, щоб модель навчилася добре прогнозувати ціни. Тому повторіть процес навчання **100 разів**.

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить дані про квартири.
3. Створіть тензор `y_true`, який містить реальні реальні ціни.
4. Створіть цикл, який виконається **100 разів**.
5. На кожній ітерації циклу:
   * отримайте прогноз моделі `y_pred`;
   * обчисліть помилку за допомогою функції `loss_fn()`;
   * виведіть помилку на екран;
   * передайте помилку в метод `teacher.teach()`, щоб виконати один крок навчання.
    
6. Після завершення циклу ще раз отримайте прогноз моделі.
7. Виведіть:
   * прогнозовані заробітні плати;
   * значення функції втрат.
    
8. Порівняйте отримані прогнози з реальними ціни. Зробіть висновок, чи покращилася точність моделі після 100 кроків навчання.
9. Cпробуйте зменшити навчальний крок в `teacher`

In [14]:
model = NeuralNetwork(device=device)
teacher = Teacher(model, lr=0.0001)

X = torch.tensor([
    [40.0, 1.0],
    [60.0, 3.0],
    [100.0, 2.0]
], dtype=torch.float32, device=device)

y_true = torch.tensor([
    [210.0],
    [310.0],
    [360.0]
], dtype=torch.float32, device=device)

for i in range(100):
    y_pred = model.predict(X)
    loss = loss_fn(y_pred, y_true)

    print(i + 1, loss.item())

    teacher.teach(loss)

y_pred = model.predict(X)
loss = loss_fn(y_pred, y_true)

print("Прогнозовані ціни:")
print(y_pred)

print("Реальні ціни:")
print(y_true)

print("Фінальна помилка:")
print(loss)

1 60.0
2 59.92888641357422
3 59.857757568359375
4 59.7866325378418
5 59.71550750732422
6 59.644378662109375
7 59.573265075683594
8 59.50214767456055
9 59.4310302734375
10 59.359893798828125
11 59.288780212402344
12 59.2176513671875
13 59.14652633666992
14 59.075408935546875
15 59.004295349121094
16 58.93316650390625
17 58.86204147338867
18 58.790916442871094
19 58.71979904174805
20 58.64867401123047
21 58.57755661010742
22 58.506439208984375
23 58.4353141784668
24 58.36418914794922
25 58.293060302734375
26 58.22193908691406
27 58.15082550048828
28 58.07969284057617
29 58.008567810058594
30 57.93745040893555
31 57.86631393432617
32 57.795196533203125
33 57.724082946777344
34 57.6529655456543
35 57.58184051513672
36 57.510711669921875
37 57.4395866394043
38 57.36846160888672
39 57.29734420776367
40 57.226226806640625
41 57.155113220214844
42 57.08397674560547
43 57.01285934448242
44 56.941734313964844
45 56.870601654052734
46 56.79948425292969
47 56.728370666503906
48 56.65724182128906
4

# Завдання 10

У вашому розпорядженні є нейронна мережа, яка прогнозує **ймовірність дощу**.

Модель використовує три ознаки:

* температура повітря (°C);
* вологість повітря (%);
* швидкість вітру (км/год).

Результатом роботи моделі є **два числа**:

1. ймовірність того, що **дощу не буде**;
2. ймовірність того, що **дощ буде**.

Скористайтеся методом `predict()`, щоб визначити ймовірності для таких погодних умов:

* температура — **20°C**;
* вологість — **80%**;
* швидкість вітру — **15 км/год**.



In [16]:
import torch


class RainNeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [
                [0.03, 0.01, 0.02],
                [0.06, -0.01, 0.08]
            ],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [-0.2, -0.3],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 3:
            raise ValueError(
                f"Очікується 3 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        logits = X @ self.W.T + self.b
        return torch.softmax(logits, dim=1)

In [17]:
model = RainNeuralNetwork(device=device)

X = torch.tensor([
    [20.0, 80.0, 15.0]
], dtype=torch.float32, device=device)

with torch.no_grad():
    y_pred = model.predict(X)

print("Ймовірність без дощу:", y_pred[0, 0])
print("Ймовірність дощу:", y_pred[0, 1])

Ймовірність без дощу: tensor(0.5498, device='cuda:0')
Ймовірність дощу: tensor(0.4502, device='cuda:0')


# Завдання 11

Метеостанція надала прогноз погоди на **4 дні**.

| День | Температура (°C) | Вологість (%) | Швидкість вітру (км/год) |
| ---- | ---------------: | ------------: | -----------------------: |
| 1    |               30 |            40 |                        5 |
| 2    |               22 |            85 |                       18 |
| 3    |               15 |            95 |                       25 |
| 4    |               28 |            60 |                       10 |

Виконайте наступні кроки:

1. Створіть один тензор `X` розміру **(4, 3)**, де кожен рядок містить дані про один день.

2. За допомогою методу `predict()` отримайте ймовірності для кожного дня `y_pred`.

3. Скористайтеся функцією `torch.argmax(..., dim=1)`, щоб визначити прогноз моделі `result`:

   * `0` — дощу не буде;
   * `1` — дощ буде.

4. Виведіть:

   * тензор із ймовірностями `y_pred`;
   * тензор із прогнозами `result`


In [18]:
X = torch.tensor([
    [30.0, 40.0, 5.0],
    [22.0, 85.0, 18.0],
    [15.0, 95.0, 25.0],
    [28.0, 60.0, 10.0]
], dtype=torch.float32, device=device)

with torch.no_grad():
    y_pred = model.predict(X)

result = torch.argmax(y_pred, dim=1)

print("Ймовірності:")
print(y_pred)

print("Прогнози:")
print(result)

Ймовірності:
tensor([[0.4256, 0.5744],
        [0.5150, 0.4850],
        [0.5125, 0.4875],
        [0.4651, 0.5349]], device='cuda:0')
Прогнози:
tensor([1, 0, 0, 1], device='cuda:0')


# Завдання 12

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
| ---- | :-: |
| 1    |  Ні |
| 2    | Так |
| 3    | Так |
| 4    |  Ні |

Для навчання моделі використайте готову функцію втрат **CrossEntropyLoss** з бібліотеки **PyTorch**.

### Завдання

1. Створіть об'єкт функції втрат:

   ```python
   loss_fn = torch.nn.CrossEntropyLoss()
   ```

2. Створіть об'єкт класу `Teacher`, передавши йому модель.

3. Створіть тензор `X`, який містить погодні умови за всі 4 дні.

4. Створіть тензор `y_true`, який містить правильні відповіді:

   * `0` — дощу не було;
   * `1` — дощ був.

5. Створіть цикл, який виконається **100 разів**.

6. На кожній ітерації циклу:

   * отримайте ймовірності від моделі `y_pred`:
   * обчисліть помилку:
   * виведіть помилку
   * передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

7. Після завершення циклу ще раз отримайте прогноз моделі.

8. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:

   * `0` — дощу не буде;
   * `1` — дощ буде.

9. Виведіть:

   * ймовірності, отримані від моделі;
   * прогнози моделі (`0` або `1`);
   * правильні відповіді
   * значення функції втра


In [19]:
model = RainNeuralNetwork(device=device)

teacher = Teacher(model)

loss_fn = torch.nn.CrossEntropyLoss()

X = torch.tensor([
    [30.0, 40.0, 5.0],
    [22.0, 85.0, 18.0],
    [15.0, 95.0, 25.0],
    [28.0, 60.0, 10.0]
], dtype=torch.float32, device=device)

y_true = torch.tensor([
    0,
    1,
    1,
    0
], dtype=torch.long, device=device)

for i in range(100):
    y_pred = model.predict(X)

    loss = loss_fn(torch.log(y_pred), y_true)

    print(i + 1, loss.item())

    teacher.teach(loss)

y_pred = model.predict(X)
result = torch.argmax(y_pred, dim=1)

loss = loss_fn(torch.log(y_pred), y_true)

print("Ймовірності:")
print(y_pred)

print("Прогнози:")
print(result)

print("Правильні відповіді:")
print(y_true)

print("Фінальна помилка:")
print(loss)

1 0.765501856803894
2 8.063092231750488
3 34.921302795410156
4 26.068180084228516
5 nan
6 nan
7 nan
8 nan
9 nan
10 nan
11 nan
12 nan
13 nan
14 nan
15 nan
16 nan
17 nan
18 nan
19 nan
20 nan
21 nan
22 nan
23 nan
24 nan
25 nan
26 nan
27 nan
28 nan
29 nan
30 nan
31 nan
32 nan
33 nan
34 nan
35 nan
36 nan
37 nan
38 nan
39 nan
40 nan
41 nan
42 nan
43 nan
44 nan
45 nan
46 nan
47 nan
48 nan
49 nan
50 nan
51 nan
52 nan
53 nan
54 nan
55 nan
56 nan
57 nan
58 nan
59 nan
60 nan
61 nan
62 nan
63 nan
64 nan
65 nan
66 nan
67 nan
68 nan
69 nan
70 nan
71 nan
72 nan
73 nan
74 nan
75 nan
76 nan
77 nan
78 nan
79 nan
80 nan
81 nan
82 nan
83 nan
84 nan
85 nan
86 nan
87 nan
88 nan
89 nan
90 nan
91 nan
92 nan
93 nan
94 nan
95 nan
96 nan
97 nan
98 nan
99 nan
100 nan
Ймовірності:
tensor([[nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan]], device='cuda:0', grad_fn=<SoftmaxBackward0>)
Прогнози:
tensor([0, 0, 0, 0], device='cuda:0')
Правильні відповіді:
tensor([0, 1, 1, 0], device='cuda:0')
Фіна

# Завдання 13

Попробуйте натренувати модель використовуючи функцію втрат, яку ви раніше застосовували для задачі визначення цін на квартири (`torch.nn.MSELoss()`), замість `CrossEntropyLoss`.

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
|------|-----|
| 1    | Ні  |
| 2    | Так |
| 3    | Так |
| 4    | Ні  |

**Завдання**

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить погодні умови за всі 4 дні.
3. Створіть тензор `y_true` розміром (4, 2), де кожен рядок містить інформацію про те чи йшов дощ в цей день:
   - `[1, 0]` — дощу не було
   - `[0, 1]` — дощ був
   -  формат інший тому що ваша функція вимагає щоб `y_true` та `y_pred` були однакового розміру
4. Створіть цикл, який виконається 100 разів.

На кожній ітерації циклу:
- отримайте ймовірності від моделі `y_pred`;
- обчисліть помилку;
- виведіть помилку;
- передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

6. Після завершення циклу ще раз отримайте прогноз моделі.
7. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:
   - 0 — дощу не буде;
   - 1 — дощ буде.

**Виведіть:**
- ймовірності, отримані від моделі;
- прогнози моделі (0 або 1);
- правильні відповіді;
- значення функції втрат.


In [20]:
model = RainNeuralNetwork(device=device)

teacher = Teacher(model)

loss_fn = torch.nn.MSELoss()

X = torch.tensor([
    [30.0, 40.0, 5.0],
    [22.0, 85.0, 18.0],
    [15.0, 95.0, 25.0],
    [28.0, 60.0, 10.0]
], dtype=torch.float32, device=device)

y_true = torch.tensor([
    [1.0, 0.0],
    [0.0, 1.0],
    [0.0, 1.0],
    [1.0, 0.0]
], dtype=torch.float32, device=device)

for i in range(100):
    y_pred = model.predict(X)

    loss = loss_fn(y_pred, y_true)

    print(i + 1, loss.item())

    teacher.teach(loss)

y_pred = model.predict(X)
result = torch.argmax(y_pred, dim=1)

loss = loss_fn(y_pred, y_true)

print("Ймовірності:")
print(y_pred)

print("Прогнози:")
print(result)

print("Правильні відповіді:")
print(torch.argmax(y_true, dim=1))

print("Фінальна помилка:")
print(loss)

1 0.28600552678108215
2 0.4990983009338379
3 0.4990118741989136
4 0.4989076852798462
5 0.4987797141075134
6 0.4986189603805542
7 0.49841147661209106
8 0.4981343150138855
9 0.4977468252182007
10 0.49717116355895996
11 0.4962388277053833
12 0.49451708793640137
13 0.4905555546283722
14 0.4765602946281433
15 0.34930047392845154
16 0.4998522102832794
17 0.4998437166213989
18 0.49983417987823486
19 0.4998234510421753
20 0.4998112916946411
21 0.4997973144054413
22 0.49978113174438477
23 0.49976223707199097
24 0.4997398853302002
25 0.49971291422843933
26 0.49967989325523376
27 0.4996386766433716
28 0.49958568811416626
29 0.49951520562171936
30 0.49941739439964294
31 0.4992733597755432
32 0.49904289841651917
33 0.4986242651939392
34 0.49768397212028503
35 0.49445652961730957
36 0.4586906433105469
37 0.3014705181121826
38 0.4729996621608734
39 0.013474327512085438
40 0.15621216595172882
41 0.4985002875328064
42 0.49825718998908997
43 0.49792540073394775
44 0.49744826555252075
45 0.49671107530593